Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')
             CRIM          ZN       INDUS        CHAS         NOX          RM  ...         DIS         RAD         TAX     PTRATIO           B       LSTAT
count  486.000000  486.000000  486.000000  486.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000  506.000000  506.000000  486.000000
mean     3.611874   11.211934   11.083992    0.069959    0.554695    6.284634  ...    3.795043    9.549407  408.237154   18.455534  356.674032   12.715432
std      8.720192   23.388876    6.835896    0.255340    0.115878    0.702617  ...    2.105710    8.707259  168.537116    2.164946   91.294864    7.155871
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000  ...    1.129600    1.000000  187.000000   12.600000    0.320000    1.730000
25%      0.081900    0.000000    5.190000    0.000000    0.449000    5.885500  ...    2.100175    4.000000  279.000000   17.400000  375.377500    7.125000
50%      0.253715    0.000000    9.690000    0.000000    0.538000    6.208500  ...    3.207450    5.000000  330.000000   19.050000  391.440000   11.430000
75%      3.560262   12.500000   18.100000    0.000000    0.624000    6.623500  ...    5.188425   24.000000  666.000000   20.200000  396.225000   16.955000
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000  ...   12.126500   24.000000  711.000000   22.000000  396.900000   37.970000

[8 rows x 13 columns]
Traceback (most recent call last):
  File "q3.py", line 52, in <module>
    mlp.fit(X_train, y_train, epochs=500, batch_size=32)
  File "/home/mananchichra/Downloads/SMAI_ASSIGNMENT/models/MLP/MLPReg.py", line 102, in fit
    self.backward(X_batch, y_batch)
  File "/home/mananchichra/Downloads/SMAI_ASSIGNMENT/models/MLP/MLPReg.py", line 75, in backward
    dz = self.a[-1] - y  # Output layer error
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 682, in __array_ufunc__
    result = ops.maybe_dispatch_ufunc_to_dunder_op(
  File "pandas/_libs/ops_dispatch.pyx", line 91, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 345, in wrapper
    return left._construct_result(result, name=res_name)
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 2757, in _construct_result
    out = self._constructor(result, index=self.index)
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 327, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/home/mananchichra/anaconda3/lib/python3.8/site-packages/pandas/core/construction.py", line 496, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
